apiVersion: batch/v1
kind: CronJob
metadata:
  name: backend-cronjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: kcleung235/lottery:latest
            imagePullPolicy: IfNotPresent
            command:
            - node
            - /dist/cmd.js
          restartPolicy: OnFailure